name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: go build -o GitLab-Importer ./cmd/main.go

      - name: Archive the binary
        run: zip GitLab-Importer.zip GitLab-Importer

      - name: Generate Changelog Notes
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: .github/release-changelog-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GitLab-Importer.zip
          asset_name: GitLab-Importer.zip
          asset_content_type: application/zip
