name: Build and Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for changelog generation to work

      - name: Fetch all tags
        run: git fetch --prune --unshallow --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          PLATFORMS=("linux amd64" "windows amd64" "darwin amd64")

          for platform in "${PLATFORMS[@]}"; do
            read -r os arch <<< "$platform"
            echo "Building for $os/$arch..."
            
            binary_name="GitLab-Importer"
            if [ "$os" = "windows" ]; then
              binary_name="$binary_name.exe"
            fi
            
            GOOS=$os GOARCH=$arch go build -ldflags="-X main.Version=${GITHUB_REF#refs/tags/}" \
              -o "build/$binary_name-$os-$arch$([[ $os = "windows" ]] && echo ".exe" || echo "")" \
              ./cmd/main.go
          done

      - name: Create Archives
        run: |
          cd build
          for file in GitLab-Importer-*; do
            zip "${file}.zip" "$file"
          done

      - name: Move Changelog Config
        run: |
          mkdir -p .github
          cp release-changelog-config.yml .github/release-changelog-config.yml

      - name: Generate Changelog Notes
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: .github/release-changelog-config.yml
          failOnError: false
          fromTag: ${{ github.ref_name }}
          toTag: ${{ github.event.before }}
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: success()
        with:
          token: ${{ secrets.ORIGIN_TOKEN }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: |
            ## What's Changed
            ${{ steps.changelog.outputs.changelog }}

            For full changelog, see the [commits since previous release](https://github.com/${{ github.repository }}/compare/${{ github.event.before }}...${{ github.ref_name }})
          draft: false
          prerelease: false
          files: build/*.zip
