name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Build
        run: |
          # Build for multiple platforms
          GOOS=linux GOARCH=amd64 go build -ldflags="-X main.Version=${{ github.ref_name }}" -o GitLab-Importer-linux-amd64 ./cmd/main.go
          GOOS=windows GOARCH=amd64 go build -ldflags="-X main.Version=${{ github.ref_name }}" -o GitLab-Importer-windows-amd64.exe ./cmd/main.go
          GOOS=darwin GOARCH=amd64 go build -ldflags="-X main.Version=${{ github.ref_name }}" -o GitLab-Importer-darwin-amd64 ./cmd/main.go
          
          # Create archives
          zip GitLab-Importer-linux-amd64.zip GitLab-Importer-linux-amd64
          zip GitLab-Importer-windows-amd64.zip GitLab-Importer-windows-amd64.exe
          zip GitLab-Importer-darwin-amd64.zip GitLab-Importer-darwin-amd64
          
          # Generate checksums
          sha256sum GitLab-Importer-*.zip > checksums.txt

      - name: Generate Changelog Notes
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v2
        with:
          configuration: .github/release-changelog-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ORIGIN_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./GitLab-Importer.zip
          asset_name: GitLab-Importer.zip
          asset_content_type: application/zip
