name: Run Go App Daily
on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.23.1'
      - env:
          TEST: ${{ secrets.TEST }}
      - name: Build
        run: go build -o importer
      - name: print
        run: echo $TEST
      - name: Run App
        run: ./importer
